hotwireapp/config/routes.rb
Rails.application.routes.draw do
  get "pages/home"
  resources :urls

  get "up" => "rails/health#show", as: :rails_health_check

  root "pages#home"
end

hotwireapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

hotwireapp/app/models/url.rb
class Url < ApplicationRecord
end

hotwireapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

hotwireapp/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

hotwireapp/app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: %i[ show edit update destroy ]

  # GET /urls
  def index
    @urls = Url.all
  end

  # GET /urls/1
  def show
  end

  # GET /urls/new
  def new
    @url = Url.new
  end

  # GET /urls/1/edit
  def edit
  end

  # POST /urls
  def create
    @url = Url.new(url_params)

    if @url.save
      redirect_to @url, notice: "Url was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /urls/1
  def update
    if @url.update(url_params)
      redirect_to @url, notice: "Url was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /urls/1
  def destroy
    @url.destroy!
    redirect_to urls_path, notice: "Url was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def url_params
      params.expect(url: [ :title, :link, :description ])
    end
end

hotwireapp/app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_when_native
    "hidden" if hotwire_native_app?
  end
end

hotwireapp/app/helpers/pages_helper.rb
module PagesHelper
end

hotwireapp/app/helpers/urls_helper.rb
module UrlsHelper
end

hotwireapp/app/views/layouts/_navbar.html.erb
<nav class="w-full bg-blue-600">
    <div class="container mx-auto px-4">
         <div class="flex justify-between items-center h-16">
            <div>
              <%= link_to "Hotwire App", root_url, class: "text-white text-lg font-semibold hover:text-purple-200" %>
            </div>
            <div class="flex space-x-6">
              <%= link_to "URLs", urls_path, class: "text-white hover:text-purple-200", data: { turbo_action: "replace" } %>
            </div>
        </div>
    </div>
</nav>

hotwireapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Hotwireapp" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

hotwireapp/app/views/pages/home.html.erb
<div>
  <h1 class="font-bold text-4xl">Pages#home</h1>
  <p>Find me in app/views/pages/home.html.erb</p>
</div>

hotwireapp/app/views/urls/_form.html.erb
<%= form_with(model: url, class: "contents") do |form| %>
  <% if url.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
        <% url.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :link %>
    <%= form.text_field :link, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.textarea :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

hotwireapp/app/views/urls/_url.html.erb
<div id="<%= dom_id url %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= url.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Link:</strong>
    <%= url.link %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= url.description %>
  </p>

</div>

hotwireapp/app/views/urls/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing url</h1>

  <%= render "form", url: @url %>

  <%= link_to "Show this url", @url, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to urls", urls_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

hotwireapp/app/views/urls/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Urls" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Urls</h1>
    <%= link_to "New url", new_url_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium #{hidden_when_native}", 
        data: { controller: "button", bridge_title: "New Url" } %>
  </div>

  <div id="urls" class="min-w-full">
    <% @urls.each do |url| %>
      <%= render url %>
      <p>
        <%= link_to "Show this url", url, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

hotwireapp/app/views/urls/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New url</h1>

  <%= render "form", url: @url %>

  <%= link_to "Back to urls", urls_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

hotwireapp/app/views/urls/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @url %>

    <%= link_to "Edit this url", edit_url_path(@url), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to urls", urls_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this url", @url, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>